<?php
declare(strict_types=1);
require_once __DIR__ . '/bootstrap.php';

function custodyRow(array $r): array { return ['id'=>(int)$r['id'],'docNumber'=>$r['doc_number'],'productId'=>(int)$r['product_id'],'quantity'=>(int)$r['quantity'],'issueDate'=>$r['issue_date'],'holder'=>$r['holder'],'unit'=>$r['unit'],'expectedReturn'=>$r['expected_return'],'conditionOut'=>$r['condition_out'],'notes'=>$r['notes'],'status'=>$r['status'],'returnDate'=>$r['return_date'],'conditionIn'=>$r['condition_in'],'returnNotes'=>$r['return_notes'],'returnDocNumber'=>$r['return_doc_number'],'voidReason'=>$r['void_reason']]; }
function reasonRequired(mixed $v): string { $s=trim((string)$v); if($s==='') throw new BusinessError('علت این عملیات الزامی است'); return $s; }

try {
 $user=requireUser($auth); $method=$_SERVER['REQUEST_METHOD']; $body=requestBody(); $path=parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH)?:'';
 if($method==='GET'&&preg_match('~/api/custody/?$~',$path)){ $rows=$db->all('SELECT * FROM custody_records ORDER BY id DESC'); jsonResponse(['custodyRecords'=>array_map('custodyRow',$rows)]); }
 if($method==='POST'&&preg_match('~/api/custody/(\d+)/return/?$~',$path,$m)){
  $id=(int)$m[1];$date=trim((string)($body['date']??''));$condition=(string)($body['conditionIn']??'');$notes=trim((string)($body['notes']??''));if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))throw new BusinessError('تاریخ بازگشت نامعتبر است');if(!in_array($condition,['سالم','آسیب‌دیده','نیازمند تعمیر','مفقود'],true))throw new BusinessError('وضعیت بازگشت نامعتبر است');if(in_array($condition,['آسیب‌دیده','مفقود'],true)&&$notes==='')throw new BusinessError('برای وضعیت آسیب‌دیده یا مفقود، ثبت توضیحات الزامی است');
  $result=$db->transaction(function(Database $db)use($id,$date,$condition,$notes,$user){$r=$db->one('SELECT * FROM custody_records WHERE id=? FOR UPDATE',[$id]);if(!$r)throw new BusinessError('رکورد امانت یافت نشد',404);if($r['status']!=='باز')throw new BusinessError('این رکورد قبلاً تسویه یا باطل شده است');if($date<$r['issue_date'])throw new BusinessError('تاریخ بازگشت نمی‌تواند قبل از تاریخ تحویل باشد');$p=$db->one('SELECT * FROM products WHERE id=? FOR UPDATE',[$r['product_id']]);$b=new Business($db);$returnDoc=$b->nextDocNumber('custReturn');$now=gmdate('c');$db->execute("UPDATE custody_records SET status='بسته',return_date=?,condition_in=?,return_notes=?,return_doc_number=? WHERE id=?",[$date,$condition,$notes,$returnDoc,$id]);$extra=[];
   if($condition==='مفقود'){$b->applyStockDelta((int)$p['id'],-(int)$r['quantity'],'ثبت مفقودی ابزار');$out=$b->nextDocNumber('out');$db->execute("INSERT INTO transactions (doc_number,product_id,type,quantity,date,requesting_unit,receiver,reason,description,created_by_user_id,created_at) VALUES (?,?,'خروج',?,?,?,?,?,?,?)",[$out,$p['id'],$r['quantity'],$date,$r['unit'],$r['holder'],'ضایعات','کسر موجودی به دلیل مفقودی ابزار امانی (سند امانت مرجع: '.$r['doc_number'].')',$user['id'],$now]);$extra=['stockAdjusted'=>true,'outDocNumber'=>$out];}
   elseif($condition==='نیازمند تعمیر'){$rep=$b->nextDocNumber('repIn');$db->execute("INSERT INTO repair_records (doc_number,product_id,quantity,send_date,submitted_by,repair_shop,issue_description,status,source_custody_id,created_by_user_id,created_at) VALUES (?,?,?,?,?,?,?,'در حال تعمیر',?,?,?)",[$rep,$r['product_id'],$r['quantity'],$date,$r['holder'],'کارگاه تعمیرات داخلی','ایجاد خودکار پس از بازگشت از امانت (سند امانت: '.$r['doc_number'].'). شرح: '.($notes?:'-'),$r['id'],$user['id'],$now]);$extra=['repairDocNumber'=>$rep];}
   $row=$db->one('SELECT * FROM custody_records WHERE id=?',[$id]);return ['row'=>$row,'returnDocNumber'=>$returnDoc,'extra'=>$extra];});
  jsonResponse(['custodyRecord'=>custodyRow($result['row']),'returnDocNumber'=>$result['returnDocNumber'],...$result['extra']]);
 }
 if($method==='PUT'&&preg_match('~/api/custody/(\d+)/?$~',$path,$m)){
  $id=(int)$m[1];$qty=(int)($body['quantity']??0);$holder=trim((string)($body['holder']??''));$unit=trim((string)($body['unit']??''));$expected=$body['expectedReturn']??null;$notes=$body['notes']??null;$reason=reasonRequired($body['reason']??'');if($qty<=0||$holder===''||$unit==='')throw new BusinessError('اطلاعات امانت ناقص است');
  $row=$db->transaction(function(Database $db)use($id,$qty,$holder,$unit,$expected,$notes,$reason,$user){$r=$db->one('SELECT * FROM custody_records WHERE id=? FOR UPDATE',[$id]);if(!$r)throw new BusinessError('رکورد امانت یافت نشد',404);if($r['status']!=='باز')throw new BusinessError('فقط امانت‌های باز قابل ویرایش هستند');$p=$db->one('SELECT * FROM products WHERE id=? FOR UPDATE',[$r['product_id']]);if($qty>(int)$r['quantity']){$snap=(new Business($db))->stockSnapshot($p);if($qty-(int)$r['quantity']>$snap['available'])throw new BusinessError('افزایش تعداد ممکن نیست؛ موجودی قابل تخصیص کافی نیست');}$db->execute('UPDATE custody_records SET quantity=?,holder=?,unit=?,expected_return=?,notes=? WHERE id=?',[$qty,$holder,$unit,$expected,$notes,$id]);$changes='اطلاعات سند امانت اصلاح شد.';(new Business($db))->addAuditEntry(['action'=>'ویرایش امانت','docNumber'=>$r['doc_number'],'changeDescription'=>$changes,'reason'=>$reason,'userId'=>$user['id']]);return $db->one('SELECT * FROM custody_records WHERE id=?',[$id]);});jsonResponse(['custodyRecord'=>custodyRow($row)]);
 }
 if($method==='POST'&&preg_match('~/api/custody/(\d+)/void/?$~',$path,$m)){$id=(int)$m[1];$reason=reasonRequired($body['reason']??'');$db->transaction(function(Database $db)use($id,$reason,$user){$r=$db->one('SELECT * FROM custody_records WHERE id=? FOR UPDATE',[$id]);if(!$r)throw new BusinessError('رکورد امانت یافت نشد',404);if($r['status']!=='باز')throw new BusinessError('فقط امانت باز قابل ابطال است');$db->execute("UPDATE custody_records SET status='باطل',void_reason=? WHERE id=?",[$reason,$id]);(new Business($db))->addAuditEntry(['action'=>'ابطال سند امانت','docNumber'=>$r['doc_number'],'changeDescription'=>'سند امانت '.$r['doc_number'].' باطل شد؛ ابزار به موجودی قابل تخصیص بازگشت.','reason'=>$reason,'userId'=>$user['id']]);});jsonResponse(['ok'=>true]);}
 if($method==='POST'&&preg_match('~/api/custody/issue/?$~',$path)){ $pid=(int)($body['productId']??0);$qty=(int)($body['quantity']??0);$date=trim((string)($body['date']??''));$holder=trim((string)($body['holder']??''));$unit=trim((string)($body['unit']??''));$expected=$body['expectedReturn']??null;$condition=$body['conditionOut']??'سالم';$notes=$body['notes']??null;if($pid<=0||$qty<=0||$date===''||$holder===''||$unit==='')throw new BusinessError('اطلاعات امانت ناقص است');if($expected&&$expected<$date)throw new BusinessError('موعد بازگشت نمی‌تواند قبل از تاریخ تحویل باشد');$row=$db->transaction(function(Database $db)use($pid,$qty,$date,$holder,$unit,$expected,$condition,$notes,$user){$p=$db->one('SELECT * FROM products WHERE id=? FOR UPDATE',[$pid]);if(!$p)throw new BusinessError('ابزار یافت نشد',404);if(!(int)$p['active'])throw new BusinessError('این ابزار بایگانی شده است');if($p['type']!=='قابل‌برگشت')throw new BusinessError('این کالا از نوع قابل‌برگشت نیست');$snap=(new Business($db))->stockSnapshot($p);if($qty>$snap['available'])throw new BusinessError('موجودی قابل تحویل کافی نیست');$b=new Business($db);$doc=$b->nextDocNumber('custIssue');$now=gmdate('c');$db->execute("INSERT INTO custody_records (doc_number,product_id,quantity,issue_date,holder,unit,expected_return,condition_out,notes,status,created_by_user_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,'باز',?,?)",[$doc,$pid,$qty,$date,$holder,$unit,$expected,$condition,$notes,$user['id'],$now]);return $db->one('SELECT * FROM custody_records WHERE id=?',[$db->lastInsertId()]);});jsonResponse(['custodyRecord'=>custodyRow($row)],201);}
 jsonResponse(['error'=>'Method Not Allowed'],405);
}catch(BusinessError $e){jsonResponse(['error'=>$e->getMessage()],$e->status);}catch(Throwable $e){error_log('custody.php: '.$e->getMessage());jsonResponse(['error'=>'خطای داخلی سرور'],500);}
