<?php
declare(strict_types=1);
require_once __DIR__ . '/bootstrap.php';

function reportProduct(Database $db, Business $business, array $p): array {
    $snap=$business->stockSnapshot($p);
    return ['id'=>(int)$p['id'],'code'=>$p['code'],'name'=>$p['name'],'type'=>$p['type'],'unit'=>$p['unit'],'stock'=>(int)$p['stock'],'minStock'=>(int)$p['min_stock'],'usageLocation'=>$p['usage_location'],'shelf'=>$p['shelf'],'description'=>$p['description'],'inCustody'=>$snap['inCustody'],'inRepair'=>$snap['inRepair'],'available'=>$snap['available'],'status'=>$business->getStockStatus($p)];
}
function reportDate(mixed $v,string $label,bool $optional=false): ?string { $s=trim((string)$v);if($s===''&&$optional)return null;if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$s))throw new BusinessError($label.' نامعتبر است');return $s; }
try{
 $user=requireUser($auth);$path=parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH)?:'';$q=$_GET;
 if($path==='/api/reports/shortage'){$level=$q['level']??'both';if(!in_array($level,['both','critical','warn'],true))throw new BusinessError('سطح گزارش نامعتبر است');$products=$db->all('SELECT * FROM products WHERE active=1 ORDER BY code');$critical=[];$warn=[];foreach($products as $p){$s=$business->getStockStatus($p);if($s==='critical')$critical[]=reportProduct($db,$business,$p);elseif($s==='warn')$warn[]=reportProduct($db,$business,$p);} $body=[];if($level==='both'||$level==='critical')$body['critical']=$critical;if($level==='both'||$level==='warn')$body['warn']=$warn;jsonResponse($body);}
 if($path==='/api/reports/kardex'){$pid=filter_var($q['productId']??0,FILTER_VALIDATE_INT);if(!$pid||$pid<1)throw new BusinessError('شناسه کالا نامعتبر است');$start=reportDate($q['startDate']??'','تاریخ شروع',true);$end=reportDate($q['endDate']??'','تاریخ پایان',true);$p=$db->one('SELECT * FROM products WHERE id=?',[$pid]);if(!$p)jsonResponse(['error'=>'کالا یافت نشد'],404);$tx=$db->all('SELECT * FROM transactions WHERE product_id=? ORDER BY date ASC,id ASC',[$pid]);$running=0;$entries=[];foreach($tx as $t){$voided=($t['status']??'معتبر')==='باطل';if(!$voided)$running+=($t['type']==='خروج'?-(int)$t['quantity']:(int)$t['quantity']);if($start!==null&&$t['date']<$start)continue;if($end!==null&&$t['date']>$end)continue;$entries[]=['id'=>(int)$t['id'],'docNumber'=>$t['doc_number'],'type'=>$t['type'],'quantity'=>(int)$t['quantity'],'date'=>$t['date'],'counterparty'=>$t['type']==='ورود'?$t['source']:($t['type']==='مرجوعی'?$t['returned_by']:$t['receiver']),'description'=>$t['description'],'voided'=>$voided,'balance'=>$running];}jsonResponse(['product'=>reportProduct($db,$business,$p),'entries'=>$entries,'ledgerBalance'=>$running]);}
 if($path==='/api/reports/custom'){$limit=min(max((int)($q['limit']??500),1),2000);$include=($q['includeVoided']??'')==='1';$where=['1=1'];$args=[];if(!$include)$where[]="t.status='معتبر'";if(($q['startDate']??'')!==''){$where[]='t.date>=?';$args[]=reportDate($q['startDate'],'تاریخ شروع');}if(($q['endDate']??'')!==''){$where[]='t.date<=?';$args[]=reportDate($q['endDate'],'تاریخ پایان');}if(($q['requestingUnit']??'')!==''){$where[]='t.requesting_unit=?';$args[]=(string)$q['requestingUnit'];}if(($q['type']??'')!==''&&($q['type']??'')!=='all'){$where[]='t.type=?';$args[]=(string)$q['type'];}if(($q['usageLocation']??'')!==''){$where[]='p.usage_location=?';$args[]=(string)$q['usageLocation'];}if(($q['receiver']??'')!==''){$term='%'.mb_strtolower(trim((string)$q['receiver']),'UTF-8').'%';$where[]="(LOWER(COALESCE(t.receiver,'')) LIKE ? OR LOWER(COALESCE(t.returned_by,'')) LIKE ?)";array_push($args,$term,$term);} $rows=$db->all('SELECT t.*,p.name product_name,p.usage_location product_usage_location FROM transactions t LEFT JOIN products p ON p.id=t.product_id WHERE '.implode(' AND ',$where).' ORDER BY t.id DESC LIMIT '.$limit,$args);$results=array_map(fn($t)=>['docNumber'=>$t['doc_number'],'date'=>$t['date'],'productName'=>$t['product_name'],'type'=>$t['type'],'quantity'=>(int)$t['quantity'],'requestingUnit'=>$t['requesting_unit'],'party'=>$t['receiver']?:($t['returned_by']?:($t['source']??null)),'usageLocation'=>$t['product_usage_location'],'voided'=>($t['status']??'معتبر')==='باطل'],$rows);jsonResponse(['results'=>$results,'limit'=>$limit,'truncated'=>count($results)===$limit]);}
 jsonResponse(['error'=>'Not Found'],404);
}catch(BusinessError $e){jsonResponse(['error'=>$e->getMessage()],$e->status);}catch(Throwable $e){error_log('reports.php: '.$e->getMessage());jsonResponse(['error'=>'خطای داخلی سرور'],500);}
